#!/usr/bin/env python3
"""Generate the GitHub Pages literature explorer (``docs/index.html``).

The page is fully self-contained: the resolved paper database is
embedded as JSON, so it works on GitHub Pages, offline, or from a local
file. It is regenerated by ``build.py`` and checked for staleness by
``validate.py`` like every other output.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DOCS  # noqa: E402
from database import lookup  # noqa: E402
from generate_catalogue import anchor, page_for  # noqa: E402

TEMPLATE = Path(__file__).resolve().parent / "site_template.html"
KEEP = ["key", "model", "aliases", "title", "authors", "year", "venue", "doi", "arxiv", "url", "search_link", "code",
        "roles", "precursor", "multimodal", "taxonomy", "application", "methodology", "contributions", "complexity",
        "efficiency", "expressivity", "datasets", "result_tables", "advantages", "limitations", "manuscript_sections",
        "verification"]


def site_outputs(data: dict, resolved: list[dict]) -> dict[Path, str]:
    lk = lookup(data["taxonomy"])
    base = data["taxonomy"]["survey"].get("repository", "").rstrip("/") + "/blob/main/"
    papers = [{k: r[k] for k in KEEP} for r in resolved]
    payload = {
        "papers": papers,
        "labels": {k: lk[k] for k in ("setting", "pattern", "domain", "subdomain", "level", "type")},
        "subdomains": [s for d in data["taxonomy"]["application_domains"] for s in d["subdomains"]],
        "roleShort": {"taxonomy": "Architecture (D1–D4)", "application": "Application", "discussed": "Discussed in Sec. 7"},
        "counts": {r: sum(r in p["roles"] for p in resolved) for r in ("taxonomy", "application", "discussed")},
        "repoBase": base,
        "repoPages": {r["key"]: f"{base}papers/{page_for(r)}#{anchor(r)}" for r in resolved},
    }
    blob = json.dumps(payload, ensure_ascii=False, sort_keys=True)
    payload["generated"] = "data version " + hashlib.sha256(blob.encode()).hexdigest()[:10]
    js = json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")
    html = TEMPLATE.read_text(encoding="utf-8").replace("__DATA__", js)
    return {DOCS / "index.html": html}


if __name__ == "__main__":
    from build import build

    build(only=["site"])
