#!/usr/bin/env python3
"""Generate the scientific comparison tables from the paper database.

Every table is rendered three times from the same in-memory object:

* ``tables/markdown/<id>.md`` – GitHub-ready Markdown
* ``tables/latex/<id>.tex``   – booktabs LaTeX with BibTeX ``\\cite`` keys
* ``tables/csv/<id>.csv``     – flat CSV for further analysis

Rules enforced here (see README, "Table conventions"):
missing values are rendered ``NR``; performance numbers are only placed
side by side when the survey reports them from the same source paper
and protocol; derived tables state that they are derived.
"""
from __future__ import annotations

import csv
import io
import re
import sys
from collections import Counter, OrderedDict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import NR, TABLES, csv_text, md_text, tex_text  # noqa: E402
from database import SETTING_ORDER, lookup  # noqa: E402

CHECK_MD, CHECK_TEX = "✓", r"\cmark"


# ---------------------------------------------------------------------------
# Table model and renderers
# ---------------------------------------------------------------------------
@dataclass
class Cell:
    md: str
    tex: str
    csv: str

    @classmethod
    def text(cls, s: Any) -> "Cell":
        return cls(md_text(s), tex_text(s), csv_text(s))

    @classmethod
    def check(cls, flag: bool) -> "Cell":
        return cls(CHECK_MD if flag else "", CHECK_TEX if flag else "", "1" if flag else "0")

    @classmethod
    def model(cls, name: str, key: str | None, link: str | None = None, marks: str = "") -> "Cell":
        md = md_text(name) + marks
        if link and link != NR:
            md = f"[{md_text(name)}]({link}){marks}"
        tex = tex_text(name) + tex_text(marks) if marks else tex_text(name)
        if key:
            tex += "~\\cite{" + key + "}"
        return cls(md, tex, csv_text(name))


_REF_NAMES = {"tab": "Table~\\ref", "fig": "Fig.~\\ref", "sec": "Section~\\ref", "subsec": "Section~\\ref",
              "eq": "Eq.~\\eqref", "app": "Appendix~\\ref"}


def tex_refs(s: str) -> str:
    """Turn manuscript labels (tab:x, sec:x, ...) in already-escaped LaTeX into cross-references."""
    def rep(m):
        label = (m.group(1) + ":" + m.group(2)).replace("\\_", "_")
        return _REF_NAMES[m.group(1)] + "{" + label + "}"
    return re.sub(r"\b(tab|fig|subsec|sec|eq|app):((?:[A-Za-z0-9-]|\\_)+)", rep, s)


def C(x: Any) -> Cell:
    return x if isinstance(x, Cell) else Cell.text(x)


@dataclass
class Table:
    id: str
    title: str
    caption: str
    headers: list[str]
    colspec: str
    rows: list = field(default_factory=list)  # list[list[Cell]] or ("group", label)
    notes: list[str] = field(default_factory=list)
    long: bool = False
    group_header: str = "Group"
    csv_extra_headers: list[str] | None = None
    md_align: list[str] | None = None
    tex_head: str | None = None  # optional raw LaTeX header (multi-row column groups)

    def add(self, cells: list[Any]) -> None:
        self.rows.append([C(c) for c in cells])

    def group(self, label: str) -> None:
        self.rows.append(("group", label))

    # -- Markdown ---------------------------------------------------------
    def to_markdown(self) -> str:
        n = len(self.headers)
        align = self.md_align or [":---"] * n
        out = [f"## {self.title}", "", f"*{md_text(self.caption)}*", ""]
        out.append("| " + " | ".join(self.headers) + " |")
        out.append("| " + " | ".join(align) + " |")
        for r in self.rows:
            if isinstance(r, tuple):
                out.append("| **" + md_text(r[1]) + "** |" + " |" * (n - 1))
            else:
                out.append("| " + " | ".join(c.md for c in r) + " |")
        if self.notes:
            out.append("")
            out += [f"> {md_text(nn)}  " for nn in self.notes]
        out.append("")
        out.append(f"<sub>Generated by `scripts/generate_tables.py` from `data/`. Do not edit by hand. "
                   f"Formats: [LaTeX](../latex/{self.id}.tex) · [CSV](../csv/{self.id}.csv)</sub>")
        return "\n".join(out) + "\n"

    # -- LaTeX ------------------------------------------------------------
    def to_latex(self) -> str:
        n = len(self.headers)
        head = self.tex_head or (" & ".join("\\textbf{" + tex_text(h.replace("**", "")) + "}" for h in self.headers) + " \\\\")
        trace = re.findall(r"manuscript ([^)]*)\)", self.caption)
        caption = re.sub(r"\s*\(manuscript [^)]*\)", "", self.caption)
        body = []
        for r in self.rows:
            if isinstance(r, tuple):
                body.append("\\midrule")
                body.append(f"\\multicolumn{{{n}}}{{l}}{{\\textbf{{{tex_text(r[1])}}}}} \\\\")
                body.append("\\midrule")
            else:
                body.append(" & ".join(c.tex for c in r) + " \\\\")
        notes = ""
        if self.notes:
            notes = "\n\\par\\vspace{1mm}{\\footnotesize " + tex_refs(" ".join(tex_text(x) for x in self.notes)) + "}"
        hdr = (f"% Generated by scripts/generate_tables.py -- do not edit by hand.\n"
               + (f"% Traceability: manuscript {trace[0]}\n" if trace else "")
               +
               f"% Requires: booktabs, longtable, multirow, array, graphicx, amsmath, pifont (\\cmark = \\ding{{51}}).\n")
        if self.long:
            return (hdr + f"\\begingroup\\scriptsize\\setlength{{\\tabcolsep}}{{3pt}}\n"
                    f"\\begin{{longtable}}{{{self.colspec}}}\n"
                    f"\\caption{{{tex_refs(tex_text(caption))}}}\\label{{tab:repo-{self.id}}}\\\\\n"
                    f"\\toprule\n{head}\n\\midrule\n\\endfirsthead\n"
                    f"\\toprule\n{head}\n\\midrule\n\\endhead\n\\bottomrule\n\\endlastfoot\n"
                    + "\n".join(body).replace("\\midrule\n\\multicolumn", "\\multicolumn", 1)
                    + f"\n\\end{{longtable}}{notes}\n\\endgroup\n")
        body_txt = "\n".join(body)
        if body_txt.startswith("\\midrule\n"):
            body_txt = body_txt[len("\\midrule\n"):]
        return (hdr + "\\begin{table*}[htbp]\n\\centering\n"
                f"\\caption{{{tex_refs(tex_text(caption))}}}\n\\label{{tab:repo-{self.id}}}\n"
                "\\scriptsize\n\\setlength{\\tabcolsep}{3pt}\n\\renewcommand{\\arraystretch}{1.15}\n"
                f"\\resizebox{{\\textwidth}}{{!}}{{%\n\\begin{{tabular}}{{{self.colspec}}}\n\\toprule\n{head}\n\\midrule\n"
                f"{body_txt}\n\\bottomrule\n\\end{{tabular}}}}{notes}\n\\end{{table*}}\n")

    # -- CSV --------------------------------------------------------------
    def to_csv(self) -> str:
        buf = io.StringIO()
        w = csv.writer(buf, lineterminator="\n")
        has_groups = any(isinstance(r, tuple) for r in self.rows)
        heads = [h.replace("**", "") for h in (self.csv_extra_headers or self.headers)]
        w.writerow(([self.group_header] if has_groups else []) + heads)
        g = ""
        for r in self.rows:
            if isinstance(r, tuple):
                g = r[1]
                continue
            w.writerow(([csv_text(g)] if has_groups else []) + [c.csv for c in r])
        return buf.getvalue()

    def outputs(self) -> dict[Path, str]:
        return {
            TABLES / "markdown" / f"{self.id}.md": self.to_markdown(),
            TABLES / "latex" / f"{self.id}.tex": self.to_latex(),
            TABLES / "csv" / f"{self.id}.csv": self.to_csv(),
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def marks(rec: dict) -> str:
    m = ""
    if rec.get("precursor"):
        m += "†"
    if rec.get("multimodal"):
        m += "◆"
    if rec["verification"]["status"] == "needs_verification":
        m += "⚠"
    return m


def model_cell(rec: dict, with_marks: bool = True) -> Cell:
    return Cell.model(rec["model"], rec["key"], rec["primary_link"], marks(rec) if with_marks else "")


def by_key(resolved: list[dict]) -> dict[str, dict]:
    return {r["key"]: r for r in resolved}


LEGEND_MARKS = ("Markers: † structured-SSM precursor without input-dependent selection; ◆ multimodal input; "
                "⚠ record flagged for author verification (see docs/FLAGS.md). NR = not reported in the survey.")


# ---------------------------------------------------------------------------
# Individual tables
# ---------------------------------------------------------------------------
def t_taxonomy_dimensions(data: dict, resolved: list[dict]) -> Table:
    t = Table("taxonomy_dimensions", "T1 · Taxonomy dimensions",
              "Taxonomy dimensions used to classify Graph Mamba architectures (manuscript tab:taxonomy-dimensions).",
              ["Dim.", "Design question", "Architectural aspect", "Main question", "Representative design choices", "Categories"],
              "p{0.8cm}p{1.6cm}p{2.8cm}p{3.2cm}p{5.2cm}p{3.4cm}")
    for d in data["taxonomy"]["dimensions"]:
        cats = [x["label"] for x in d.get("levels", []) + d.get("types", [])]
        t.add([d["id"], d["name"], d["aspect"], d["question"], d["choices"], ", ".join(cats) if cats else "Free text (per model)"])
    t.notes = ["The four dimensions are not mutually exclusive; a model receives one label per dimension, "
               "and multiple D3/D4 labels when it combines strategies."]
    return t


def t_unified_taxonomy(data: dict, resolved: list[dict]) -> Table:
    lk = lookup(data["taxonomy"])
    t = Table("unified_taxonomy", "T2 · Unified D1–D4 taxonomy of Graph Mamba architectures",
              "Unified taxonomy of representative Graph Mamba architectures according to tokenization (D1), "
              "ordering (D2), coupling (D3), and integration (D4) (manuscript tab:unified-taxonomy).",
              ["Model", "Year", "Tokenization (D1)", "Ordering (D2)", "D3: Input", "D3: Dynamics", "D3: Operator",
               "D4: Standalone", "D4: Sequential", "D4: Parallel", "D4: Embedded"],
              "p{2.4cm}c p{3.4cm}p{3.4cm}ccccccc",
              md_align=[":---", ":---:", ":---", ":---"] + [":---:"] * 7)
    t.group_header = "Graph setting"
    rot = lambda x: "\\rotatebox{90}{" + x + "}"
    t.tex_head = ("\\multirow{2}{*}{\\textbf{Model}} & \\multirow{2}{*}{\\textbf{Year}} & "
                  "\\multirow{2}{*}{\\textbf{Tokenization (D1)}} & \\multirow{2}{*}{\\textbf{Ordering (D2)}} & "
                  "\\multicolumn{3}{c}{\\textbf{Coupling (D3)}} & \\multicolumn{4}{c}{\\textbf{Integration (D4)}} \\\\\n"
                  "\\cmidrule(lr){5-7}\\cmidrule(lr){8-11}\n& & & & "
                  + " & ".join(rot(x) for x in ["Input", "Dynamics", "Operator", "Standalone", "Sequential", "Parallel", "Embedded"])
                  + " \\\\")
    for s in SETTING_ORDER:
        recs = [r for r in resolved if r["taxonomy"] and r["taxonomy"]["setting"] == s]
        if not recs:
            continue
        t.group(lk["setting"][s])
        for r in recs:
            tx = r["taxonomy"]
            t.add([model_cell(r), r["year"], tx["d1"], tx["d2"]]
                  + [Cell.check(lv in tx["d3"]) for lv in ("input", "dynamics", "operator")]
                  + [Cell.check(ty in tx["d4"]) for ty in ("standalone", "sequential", "parallel", "embedded")])
    t.notes = ["D3 indicates where graph structure enters the state-space computation (input-, dynamics-, or "
               "operator-level coupling); D4 indicates how the state-space component is combined with "
               "graph-learning mechanisms. Multiple check marks: the architecture combines strategies.", LEGEND_MARKS]
    return t


def t_structural_tradeoffs(data: dict, resolved: list[dict]) -> Table:
    t = Table("structural_tradeoffs", "T3 · Structural and computational trade-offs per dimension",
              "Structural and computational implications of the Graph Mamba taxonomy dimensions "
              "(manuscript tab:structural-tradeoffs), with the cost term of eq:end-to-end-cost each dimension contributes.",
              ["Dim.", "Design choice", "Structural implication", "Main trade-off", "Cost term"],
              "p{0.8cm}p{2.4cm}p{4.4cm}p{6.2cm}p{1.6cm}")
    for d in data["taxonomy"]["dimensions"]:
        t.add([d["id"], f"{d['name']}: {d['aspect']}", d["structural_implication"], d["trade_off"],
               Cell(f"`{d['cost_term']}`", "$" + d["cost_term"].replace("_", "_{\\mathrm{") + "}}$", d["cost_term"])])
    t.notes = [f"Conceptual decomposition: {data['taxonomy']['cost_decomposition']}. T_graph belongs to graph "
               "construction, which the survey treats as context rather than a design question."]
    return t


def t_cross_domain(data: dict, resolved: list[dict]) -> Table:
    lk = lookup(data["taxonomy"])
    t = Table("cross_domain_applications", "T4 · Cross-domain applications and graph–SSM design patterns",
              "Cross-domain Graph Mamba applications and recurring graph--SSM design patterns "
              "(manuscript tab:cross-domain-applications and fig:design-patterns).",
              ["Work", "Year", "Task", "Graph construction", "Graph–SSM division of labor", "DV", "RT", "GS", "LG", "Dominant (secondary)"],
              "p{2.3cm}c p{2.6cm}p{3.2cm}p{5.6cm}ccccc", long=True,
              md_align=[":---", ":---:", ":---", ":---", ":---"] + [":---:"] * 5)
    t.group_header = "Domain"
    t.tex_head = ("\\multirow{2}{*}{\\textbf{Work}} & \\multirow{2}{*}{\\textbf{Year}} & \\multirow{2}{*}{\\textbf{Task}} & "
                  "\\multirow{2}{*}{\\textbf{Graph construction}} & \\multirow{2}{*}{\\textbf{Graph--SSM division of labor}} & "
                  "\\multicolumn{4}{c}{\\textbf{Pattern}} & \\multirow{2}{*}{\\textbf{Dominant}} \\\\\n"
                  "\\cmidrule(lr){6-9}\n& & & & & DV & RT & GS & LG & \\\\")
    for dom in data["taxonomy"]["application_domains"]:
        for sub in dom["subdomains"]:
            recs = [r for r in resolved if r["application"] and r["application"]["subdomain"] == sub["id"]]
            if not recs:
                continue
            t.group(f"{dom['label']} — {sub['label']}")
            for r in recs:
                a = r["application"]
                dom_txt = a["dominant_pattern"] + (f" (+{a['secondary_pattern']})" if a.get("secondary_pattern") else "")
                t.add([model_cell(r), r["year"], a["task"], a["graph_construction"], a["division_of_labor"]]
                      + [Cell.check(p in a["patterns"]) for p in ("DV", "RT", "GS", "LG")] + [dom_txt])
    t.notes = ["Patterns: DV = dual-view; RT = relational--temporal; GS = graph-guided sequence; LG = local-to-global. "
               "Multiple check marks indicate combined patterns; the dominant/secondary assignment follows fig:design-patterns.",
               LEGEND_MARKS]
    return t


def t_pattern_distribution(data: dict, resolved: list[dict]) -> Table:
    t = Table("pattern_distribution", "T5 · Distribution of dominant design patterns across application settings (derived)",
              "Number of reviewed applications per data setting and dominant design pattern. Derived automatically "
              "from the dominant-pattern labels of fig:design-patterns; secondary patterns in parentheses.",
              ["Data setting", "DV", "RT", "GS", "LG", "Total", "Precursors (†)", "Multimodal (◆)"],
              "p{5cm}ccccccc", md_align=[":---"] + [":---:"] * 7)
    apps = [r for r in resolved if r["application"]]
    tot_dom, tot_sec = Counter(), Counter()
    for dom in data["taxonomy"]["application_domains"]:
        for sub in dom["subdomains"]:
            recs = [r for r in apps if r["application"]["subdomain"] == sub["id"]]
            if not recs:
                continue
            dc = Counter(r["application"]["dominant_pattern"] for r in recs)
            sc = Counter(r["application"].get("secondary_pattern") for r in recs if r["application"].get("secondary_pattern"))
            tot_dom.update(dc)
            tot_sec.update(sc)
            cells = [f"{dc.get(p, 0)}" + (f" (+{sc[p]})" if sc.get(p) else "") for p in ("DV", "RT", "GS", "LG")]
            t.add([sub["label"]] + cells + [len(recs), sum(r["precursor"] for r in recs), sum(r["multimodal"] for r in recs)])
    t.add([Cell("**Total**", "\\textbf{Total}", "Total")]
          + [f"{tot_dom.get(p, 0)}" + (f" (+{tot_sec[p]})" if tot_sec.get(p) else "") for p in ("DV", "RT", "GS", "LG")]
          + [len(apps), sum(r["precursor"] for r in apps), sum(r["multimodal"] for r in apps)])
    t.notes = ["Derived statistic (not a manuscript table). Counts dominant patterns only; '+n' gives secondary-pattern assignments."]
    return t


def t_coupling_integration(data: dict, resolved: list[dict]) -> Table:
    lk = lookup(data["taxonomy"])
    levels = ["input", "dynamics", "operator"]
    types = ["standalone", "sequential", "parallel", "embedded"]
    t = Table("coupling_integration", "T6 · Coupling depth × integration type (derived)",
              "Number of architectures in tab:unified-taxonomy per graph setting, coupling level (D3) and integration "
              "type (D4). Derived automatically; an architecture with several labels is counted once per label.",
              ["Graph setting", "Models", "Input", "Dynamics", "Operator", "Standalone", "Sequential", "Parallel", "Embedded"],
              "p{4.6cm}cccccccc", md_align=[":---"] + [":---:"] * 8)
    tax = [r for r in resolved if r["taxonomy"]]
    for s in SETTING_ORDER:
        recs = [r for r in tax if r["taxonomy"]["setting"] == s]
        t.add([lk["setting"][s], len(recs)]
              + [sum(lv in r["taxonomy"]["d3"] for r in recs) for lv in levels]
              + [sum(ty in r["taxonomy"]["d4"] for r in recs) for ty in types])
    t.add([Cell("**All settings**", "\\textbf{All settings}", "All settings"), len(tax)]
          + [sum(lv in r["taxonomy"]["d3"] for r in tax) for lv in levels]
          + [sum(ty in r["taxonomy"]["d4"] for r in tax) for ty in types])
    # cross matrix as additional rows
    t.group("Cross-tabulation D3 level × D4 type (all settings)")
    for lv in levels:
        na = Cell("–", "--", "")
        t.add([lk["level"][lv], sum(lv in r["taxonomy"]["d3"] for r in tax), na, na, na]
              + [sum(lv in r["taxonomy"]["d3"] and ty in r["taxonomy"]["d4"] for r in tax) for ty in types])
    t.notes = ["Derived statistic (not a manuscript table). It reproduces the manuscript's observation that most models "
               "couple graph structure at the input or dynamics level, operator-level coupling is uncommon, and "
               "standalone/parallel integration dominates."]
    return t


def t_benchmarks(data: dict, resolved: list[dict]) -> Table:
    bk = by_key(resolved)
    t = Table("benchmark_summary", "T7 · Benchmarks used in the comparative analysis",
              "Representative benchmarks used to evaluate Graph Mamba models (manuscript tab:benchmark-summary).",
              ["Benchmark(s)", "Domain / task", "Graph setting", "Main metrics", "Representative models", "Numeric results"],
              "p{2.6cm}p{2.6cm}p{2.8cm}p{1.8cm}p{4.2cm}p{1.8cm}")
    for b in data["benchmarks"]["benchmarks"]:
        models_md = ", ".join(f"[{md_text(bk[k]['model'])}](../../papers/{_page_for(bk[k])}#{anchor(bk[k])})" for k in b["models"] if k in bk)
        models_tex = ", ".join(f"{tex_text(bk[k]['model'])}~\\cite{{{k}}}" for k in b["models"] if k in bk)
        models_csv = "; ".join(bk[k]["model"] for k in b["models"] if k in bk)
        res = b.get("results_table")
        res_cell = Cell(f"[{res}]({res}.md)", f"Table~\\ref{{tab:repo-{res}}}", res) if res else Cell.text(NR)
        t.add([", ".join(b["datasets"]), b["domain_task"], b["graph_setting"], ", ".join(b["metrics"]),
               Cell(models_md, models_tex, models_csv), res_cell])
    leg = "; ".join(f"{k} = {v}" for k, v in data["benchmarks"]["metric_legend"].items())
    t.notes = [f"Metrics: {leg}.", "Identical metrics do not imply directly comparable experimental conditions across rows."]
    return t


def t_efficiency(data: dict, resolved: list[dict]) -> Table:
    t = Table("efficiency_summary", "T8 · Reported complexity, efficiency, and scalability evidence",
              "Reported complexity (sec. 4.3) and efficiency/scalability evidence (manuscript tab:efficiency-summary). "
              "Scan complexity and end-to-end scalability are reported separately.",
              ["Model", "Reported complexity", "Reported scaling", "Additional cost sources", "Reported evidence"],
              "p{2.2cm}p{4.0cm}p{2.6cm}p{3.2cm}p{4.6cm}")
    for r in resolved:
        if not (r["efficiency"] or r["complexity"] != NR):
            continue
        e = r["efficiency"] or {}
        t.add([model_cell(r), r["complexity"], e.get("scaling", NR), e.get("additional_costs", NR), e.get("evidence", NR)])
    t.notes = ["Evidence is configuration-specific and taken from the original publications; it does not establish "
               "complete-pipeline scalability for other settings. NR = not reported in the survey."]
    return t


def t_expressivity(data: dict, resolved: list[dict]) -> Table:
    t = Table("expressivity", "T9 · Theoretical expressive-power results",
              "Theoretical expressive-power results reported for SSM-based graph models, with message-passing GNNs "
              "and graph Transformers as references (manuscript tab:expressivity). PE/SE: positional/structural encodings.",
              ["Model", "Permutation property", "Reported result", "Caveat"],
              "p{2.8cm}p{2.8cm}p{6.0cm}p{5.0cm}")
    t.group("Reference model families")
    for ref in data["taxonomy"]["expressivity_references"]:
        t.add([Cell(md_text(ref["model"]), tex_text(ref["model"]) + "~\\cite{" + ",".join(ref["keys"]) + "}", ref["model"]),
               ref["permutation_property"], ref["result"], ref["caveat"]])
    t.group("SSM-based graph models")
    for r in resolved:
        if r["expressivity"]:
            x = r["expressivity"]
            t.add([model_cell(r), x["permutation_property"], x["result"], x["caveat"]])
    t.notes = ["For serialization-based models, separating WL-indistinguishable graphs may stem from symmetry breaking "
               "by the imposed ordering; expressive power should be characterized under an explicit invariance requirement."]
    return t


def t_future(data: dict, resolved: list[dict]) -> Table:
    bk = by_key(resolved)
    t = Table("future_directions", "T10 · Open challenges and research directions",
              "Open challenges and future research directions for Graph Mamba (manuscript tab:future-directions).",
              ["Challenge", "Design question", "Promising directions", "Early work / examples"],
              "p{3.0cm}p{2.2cm}p{7.2cm}p{4.6cm}")
    for c in data["challenges"]:
        md_parts, tex_parts, csv_parts = [], [], []
        for e in c["early_work"]:
            scope = f" ({e['scope']})" if e.get("scope") else ""
            if e["key"] in bk:
                md_parts.append(f"[{md_text(e['label'])}](../../papers/{_page_for(bk[e['key']])}#{anchor(bk[e['key']])}){md_text(scope)}")
            else:
                md_parts.append(md_text(e["label"]) + md_text(scope))
            tex_parts.append(f"{tex_text(e['label'])}~\\cite{{{e['key']}}}{tex_text(scope)}")
            csv_parts.append(e["label"] + scope)
        t.add([c["challenge"], ", ".join(c["design_questions"]), c["directions"],
               Cell(", ".join(md_parts), ", ".join(tex_parts), "; ".join(csv_parts))])
    return t


def anchor(rec: dict) -> str:
    return rec["key"].lower().replace("+", "").replace(".", "")


def _page_for(rec: dict) -> str:
    from generate_catalogue import page_for  # local import to avoid a cycle at module load
    return page_for(rec)


def _num(v: str | None) -> float | None:
    if v is None:
        return None
    try:
        return float(str(v).split("±")[0].strip())
    except ValueError:
        return None


def t_performance(data: dict, resolved: list[dict], spec: dict) -> Table:
    cols = spec["columns"]
    headers = ["Model"] + [f"{c['dataset']} · {c['metric']}" if c["dataset"] != "—" else c["metric"] for c in cols]
    src = by_key(resolved).get(spec["source"])
    src_name = src["model"] if src else spec["source"]
    t = Table(spec["id"], f"Published results · {spec['caption']}",
              f"{spec['caption']}. Results as reported in the {src_name} paper and transcribed in manuscript {spec['label']}; "
              "not reproduced.",
              headers, "l" + "c" * len(cols), md_align=[":---"] + [":---:"] * len(cols))
    # best per column (within this table only)
    best = []
    for j, b in enumerate(spec["better"]):
        vals = [_num(r["values"][j]) for r in spec["rows"]]
        vals = [v for v in vals if v is not None]
        best.append((min(vals) if b == "lower" else max(vals)) if vals else None)
    for r in spec["rows"]:
        key = r.get("key")
        name = r["model"] + (" ★" if r.get("gm") else "")
        mc = Cell(md_text(name), tex_text(r["model"]) + ("~\\cite{" + key + "}" if key else "") + (r" $\star$" if r.get("gm") else ""), r["model"])
        cells = [mc]
        for j, v in enumerate(r["values"]):
            if v is None:
                cells.append(Cell(NR, NR, NR))
                continue
            is_best = best[j] is not None and _num(v) == best[j]
            md_v, tex_v = md_text(v), tex_text(v)
            cells.append(Cell(f"**{md_v}**" if is_best else md_v, f"\\textbf{{{tex_v}}}" if is_best else tex_v, csv_text(v)))
        t.add(cells)
    arrows = ", ".join(f"{h}: {'↑' if b == 'higher' else '↓'}" for h, b in zip(headers[1:], spec["better"]))
    t.notes = [f"Evidence level: {spec['evidence']} published results (same source paper, datasets, and protocol). "
               "Do not compare these numbers with other tables in this repository.",
               f"Direction: {arrows}. Bold = best value per column within this table; ★ = Graph Mamba / SSM-based model.",
               f"Survey interpretation: {spec['interpretation']}"]
    return t


def t_evidence_coverage(data: dict, resolved: list[dict]) -> Table:
    t = Table("evidence_coverage", "T11 · Evidence coverage and reporting gaps (derived)",
              "Kinds of evidence the survey reports for each architecture-level work (taxonomy and discussed models). "
              "Derived automatically; it exposes the reporting gaps discussed in sec:reproducibility.",
              ["Model", "Setting", "Complexity", "Efficiency evidence", "Expressivity result", "Benchmarks named",
               "Numeric results", "Limitations stated", "Challenge link"],
              "p{2.4cm}p{2.6cm}ccccccc", md_align=[":---", ":---"] + [":---:"] * 7)
    lk = lookup(data["taxonomy"])
    for r in resolved:
        if not (r["taxonomy"] or "discussed" in r["roles"]):
            continue
        setting = lk["setting"][r["taxonomy"]["setting"]].replace(" Graph Models", "") if r["taxonomy"] else "Discussed (Sec. 7)"
        t.add([model_cell(r), setting, Cell.check(r["complexity"] != NR), Cell.check(bool(r["efficiency"])),
               Cell.check(bool(r["expressivity"])), Cell.check(bool(r["benchmarks"])), Cell.check(bool(r["result_tables"])),
               Cell.check(bool(r["limitations"])), Cell.check(bool(r["challenges"]))])
    tax = [r for r in resolved if r["taxonomy"]]
    t.notes = [f"Of {len(tax)} classified architectures, {sum(r['complexity'] != NR for r in tax)} have a complexity statement, "
               f"{sum(bool(r['efficiency']) for r in tax)} efficiency evidence, {sum(bool(r['expressivity']) for r in tax)} an "
               f"expressivity result, and {sum(bool(r['result_tables']) for r in tax)} numeric results reported in the survey. "
               "Empty cell = not reported in the survey (NR)."]
    return t


def t_paper_index(data: dict, resolved: list[dict]) -> Table:
    lk = lookup(data["taxonomy"])
    t = Table("paper_index", "T12 · Index of reviewed works",
              "All works in the paper database with bibliographic metadata resolved from references.bib.",
              ["Model", "BibTeX key", "Year", "Venue", "Role", "Category", "Link"],
              "p{2.4cm}p{3.0cm}c p{4.4cm}p{1.6cm}p{3.6cm}p{1.2cm}", long=True)
    for r in sorted(resolved, key=lambda x: (str(x["year"]), x["model"].lower())):
        if r["taxonomy"]:
            cat = lk["setting"][r["taxonomy"]["setting"]]
        elif r["application"]:
            cat = lk["subdomain"][r["application"]["subdomain"]]
        else:
            cat = "Discussed in Sec. 7"
        link = r["primary_link"]
        link_cell = Cell(f"[link]({link})" if link != NR else f"NR ([search]({r['search_link']}))",
                         f"\\url{{{link}}}" if link != NR else NR, link)
        t.add([model_cell(r), Cell(f"`{r['key']}`", "\\texttt{" + tex_text(r["key"]) + "}", r["key"]), r["year"],
               r["venue"], ", ".join(r["roles"]), cat, link_cell])
    t.notes = ["Link = DOI or arXiv URL present in references.bib; NR when absent (a Google Scholar title search is offered "
               "instead — no external metadata was added)."]
    return t


TABLE_BUILDERS = [
    t_taxonomy_dimensions, t_unified_taxonomy, t_structural_tradeoffs, t_cross_domain, t_pattern_distribution,
    t_coupling_integration, t_benchmarks, t_efficiency, t_expressivity, t_future, t_evidence_coverage, t_paper_index,
]


def build_tables(data: dict, resolved: list[dict]) -> "OrderedDict[str, Table]":
    tables: "OrderedDict[str, Table]" = OrderedDict()
    for fn in TABLE_BUILDERS:
        tb = fn(data, resolved)
        tables[tb.id] = tb
    for spec in data["results"]:
        tb = t_performance(data, resolved, spec)
        tables[tb.id] = tb
    return tables


def index_outputs(tables: "OrderedDict[str, Table]") -> dict[Path, str]:
    md = ["# Comparison tables", "",
          "All tables are generated from `data/` by `scripts/generate_tables.py`. Each is available in three formats.", "",
          "| Table | Description | Markdown | LaTeX | CSV |", "| :--- | :--- | :---: | :---: | :---: |"]
    for tid, tb in tables.items():
        md.append(f"| {tb.title} | {md_text(tb.caption)[:160]}{'…' if len(tb.caption) > 160 else ''} | "
                  f"[md](markdown/{tid}.md) | [tex](latex/{tid}.tex) | [csv](csv/{tid}.csv) |")
    md += ["", "## Using the LaTeX tables", "", "```latex", "\\usepackage{booktabs,longtable,multirow,array,graphicx,amsmath,pifont}",
           "\\newcommand{\\cmark}{\\ding{51}}", "\\input{tables/latex/unified_taxonomy}", "```", "",
           "`tables/latex/all_tables.tex` is a compilable demo document that inputs every table."]
    all_tex = ["% Generated by scripts/generate_tables.py -- compilable demo of all tables.",
               "\\documentclass[10pt]{article}", "\\usepackage[margin=1.5cm,landscape]{geometry}",
               "\\usepackage[utf8]{inputenc}", "\\usepackage[T1]{fontenc}",
               "\\usepackage{booktabs,longtable,multirow,array,graphicx,amsmath,pifont,amssymb,url}", "\\newcommand{\\cmark}{\\ding{51}}",
               "\\begin{document}"]
    all_tex += [f"\\input{{{tid}}}\\clearpage" for tid in tables]
    all_tex += ["\\bibliographystyle{plain}", "\\bibliography{../../source/references}", "\\end{document}"]
    return {TABLES / "README.md": "\n".join(md) + "\n", TABLES / "latex" / "all_tables.tex": "\n".join(all_tex) + "\n"}


def table_outputs(data: dict, resolved: list[dict]) -> tuple[dict[Path, str], "OrderedDict[str, Table]"]:
    tables = build_tables(data, resolved)
    out: dict[Path, str] = {}
    for tb in tables.values():
        out.update(tb.outputs())
    out.update(index_outputs(tables))
    return out, tables


if __name__ == "__main__":
    from build import build

    build(only=["tables"])
